### ISSUE TITLE
Crash when breaking blocks

### ISSUE THREAD

**Issue by StrutTower** [MelanX/aiotbotania#20]
I've been having the my game randomly crash when breaking blocks with the Elementium AIOT. I have it enchanted with Efficiency V and Fortune III and have mana in my inventory to repair it. It seems to happen more often when breaking gravel.

[crash-2019-02-13_20.16.54-client.txt](https://github.com/MelanX/aiotbotania/files/2865252/crash-2019-02-13_20.16.54-client.txt)

**Comment by MelanX** [comment]
Multiplayer?

**Comment by StrutTower** [comment]
I'm playing in singleplayer. I don't have a multiplayer server to test it on to see if the same thing happens.

**Comment by MelanX** [comment]
Please give me more information about Forge version
I tried on multiplayer and singleplayer with version 0.6 of AIOT Botania and no crash. I broke 1000 Gravel
Do you play AIOT Botania in a modpack? If yes, which?

**Comment by StrutTower** [comment]
I'm using a custom modpack in MultiMC

* Java 8 Update 201
* Forge 14.23.5.2807
* Botania r1.10-358
* I tried AOIT Botania v6 and v5.1
* The rest of the mods are listed in the crash report if needed.

Looks like I'm a couple version behind. I'll try updating Java, Forge, and Botania tonight. Thanks for looking into this.

**Comment by MelanX** [comment]
With your settings I get the crash :)

**Comment by StrutTower** [comment]
Upgraded to Forge 14.23.5.2814 and Botania r1.10-359 and I get the same stack trace in case that helps.

**Comment by MelanX** [comment]
Thank you. I'll test it on a server today and maybe I'm able to fix it today. I'll try :)
