### ISSUE TITLE
Super Farmland unusable

### ISSUE THREAD

**Issue by MelanX** [MelanX/aiotbotania#21]
**Versions**

Minecraft: 1.14.4
Forge: 28.0.49
Botania: not released
AIOT Botania: not released
Modpack: ---

**Describe the bug**

If you try to plant a seed on Super Farmland it isn't possible.

**How to reproduce**

1. Create Super Farmland by Elementium Hoe/AIOT
2. Try to plant a seed
3. 

**Expected behavior**

The Super Farmland behaves like the normal Farmland.

**Comment by derkalaender** [comment]
Closing, see #25
