### ISSUE TITLE
Suggestion to improve the display of AIOT modes

### ISSUE THREAD

**Issue by TheDirectorX** [MelanX/aiotbotania#27]
- [x] **Change the color of switching AIOT modes to clearer. The colors of the modes should be different from each other.**
`§6` `"gold"`: `§e` `"yellow"`
![Screenshot_2 2](https://user-images.githubusercontent.com/43481085/66238718-97473f80-e711-11e9-98be-113d8bb6dc3f.png)
`§6` `"gold"`: `§a` `"green"`
![Screenshot_2](https://user-images.githubusercontent.com/43481085/66238719-97473f80-e711-11e9-8921-cc48f27f5d38.png)
- [x] **Add the name of the mode to the AIOT description.**
![image](https://user-images.githubusercontent.com/43481085/66239242-c8743f80-e712-11e9-955e-d52b33786fcb.png)
It can be used with different colors (which I wrote about above) or as in Botania:
![image](https://user-images.githubusercontent.com/43481085/66239635-d9718080-e713-11e9-9663-65f951f9372d.png)

**Comment by MelanX** [comment]
Good idea for the next/last 1.12.2 version!
