### ISSUE TITLE
java.lang.NoSuchFieldError: SEEDS

### ISSUE THREAD

**Issue by Hoborific** [MelanX/aiotbotania#44]
**Versions**
aiotbotania-1.16.2-1.3.1.jar
Minecraft:  1.16.1
Forge: net.minecraftforge:32.0.108
Botania: Botania-1.16.1-403.1.jar 
AIOT Botania: aiotbotania-1.16.2-1.3.1.jar
Modpack: valhelsia-3

**Describe the bug**
it crashed

**How to reproduce**
sorry not a clue 

**Expected behavior**
no crash

**Screenshots**
here's a pastebin https://pastebin.com/Wm4FABut

**Comment by MelanX** [comment]
"It crashed" isn’t a good description. What did you do before it crashed? That would be nice to know.

**Comment by MelanX** [comment]
It’s because of an internal change. This versions seems to be not compatible with 1.16.1.
