### ISSUE TITLE
Error in Logs

### ISSUE THREAD

**Issue by azeroth2b** [MelanX/aiotbotania#45]
**Versions**

Minecraft: 1.16.1
Forge: 32.0.108
Botania: 1.16.1-1.3.2
AIOT Botania: 1.16.2-1.3.1
Modpack: Valhelsia 3 3.0.20

**Describe the bug**
[07:30:08] [AIOT Botania Contributor Thread/INFO] [de.me.ai.AIOTBotania/]: Oops, a wrong number at noeppi_noeppi

**How to reproduce**
Discovered in logs.

**Expected behavior**

**Screenshots**

**Comment by MelanX** [comment]
Thank you for reporting :) It’s fixed for 1.3.2 in MC 1.16.2+.
