### ISSUE TITLE
Terrasteel AIOT not working with Terrasteel armour

### ISSUE THREAD

**Issue by razgriz5000** [MelanX/aiotbotania#46]
**Versions**

Minecraft: Forge: 1.16.3
Botania: 1.16.3-408
AIOT Botania: 1.16.2-1.3.2
Modpack: 

All the mods 6 1.1.5 https://www.curseforge.com/minecraft/modpacks/all-the-mods-6
**Describe the bug**

Terrasteel AIOT does not mine blocks that cannot be insta mined.  when full terrasteel armour is worn.  Looks like it does a single hit and then resets.  
**How to reproduce**

1. Install ATM6 instance
2. give yourself terrasteel armour and terrasteel AIOT
3. Try to mine

**Expected behavior**

For the terrasteel AIOT to mine blocks

**Screenshots**

**Comment by MelanX** [comment]
Now I tried to reproduce this bug but I'm not able to do it. Could you give information about which types of blocks you tried? And in active mode or normal mode? Anything else? 
A short video could be helpful, too. Maybe a log, too.

**Comment by MDeBuff** [comment]
I'm also having this issue while using any band of Aura. (With or without the armor)

I'd suspect it has to do with the terrasteelAIOT using the depreciated IManaGivingItem instead of the TERRA_PICK_BLACKLIST tag

Terrasteel AIOT code -----------------------

`    @Override
    public boolean canReceiveManaFromItem(ItemStack stack, ItemStack otherStack) {
        return !(otherStack.getItem() instanceof IManaGivingItem);
    }
`
Current terra shatterer code ----------------------
`	@Override
	public boolean canReceiveManaFromItem(ItemStack stack, ItemStack otherStack) {
		return !otherStack.getItem().isIn(ModTags.Items.TERRA_PICK_BLACKLIST);
	}
`

**Comment by noeppi-noeppi** [comment]
I am currently fixing the alfsteel shatterer in MythicBotany. The AIOT's here have similar problems. I am going to create a pull request soon.
