### ISSUE TITLE
[1.16.4] Shears don't function as shears

### ISSUE THREAD

**Issue by NielsPilgaard** [MelanX/aiotbotania#50]
**Versions**

Minecraft: 1.16.4
Forge: 1.16.4-35.1.4
Botania: 1.16.3-409
AIOT Botania: 1.16.3-1.4.3
Modpack: 
Enigmatica 6

**Describe the bug**
When Shears are used on Grass, the Grass is not dropped.

**How to reproduce**

1. Shear Grass
2. 
3. 

**Expected behavior**
For Grass to be dropped when harvested with Shears.

The shears are also missing the `forge:shears` tag, which could be the reason for the bug tbh.

**Comment by MelanX** [comment]
Oh, I thought I added the tag. Will fix it soon, thanks for reporting

**Comment by NielsPilgaard** [comment]
Thanks :D
