### ISSUE TITLE
Terrasteel AIOT doesn't work with mana generating items

### ISSUE THREAD

**Issue by afang920** [MelanX/aiotbotania#51]
The terrasteel AIOT doesn't work when mining stone or wood whenever I have any sort of mana generating item equipped (ring of aura, set of terrasteel armor). It will mine blocks that instantly break but nothing else.

**Comment by MelanX** [comment]
That only happens if the AIOT is already damaged. It also happens with Botania tools. That's because it gets repaired and that does it make another item. Because of that the mining process will be reset. It's because of vanilla Minecraft, too much work to fix it.
