### ISSUE TITLE
Terrasteel/Alfsteel AIOT have no Crafting Recepie

### ISSUE THREAD

**Issue by Sar4h-3** [MelanX/aiotbotania#54]
We are playing with version 1.5.0 and noticed that the Terrasteel/Alfsteel AIOT have no recipe.
I dont think this is intended.

**Comment by MelanX** [comment]
Do you have Mythic Botany installed for Alfsteel AIOT?
Are the other tools craftable?
Do you have terrasteel enabled in config?

**Comment by Sar4h-3** [comment]
i have mythic Botany installed, but i didnt do anything with the config

**Comment by MelanX** [comment]
After showing in my stream, do you know what’s wrong? Can this be closed?

**Comment by Sar4h-3** [comment]
I sadly do not know whats wrong, but other issues also came up with other mods and i think this can be closed
