### ISSUE TITLE
Remove hoes in favor of those recently added in base Botania

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MelanX/aiotbotania#63]
Botania 1.16.4-414 added manasteel and elementium hoes. These have the same recipes as those added by AIOT Botania.

The AIOT recipe only accepts hoes from its own mod, which are not craftable due to a recipe conflict with the ones added by base Botania.

**Comment by MelanX** [comment]
closed by https://github.com/MelanX/aiotbotania/commit/f83596f5b56356af2bbeaaf9b3eba58e5d71afda
