### ISSUE TITLE
Terrasteel aiot

### ISSUE THREAD

**Issue by phillipnielsen** [MelanX/aiotbotania#64]
**Versions**
Minecraft: 1.16.5
Forge: 36.0.46
Botania: 1.16.4-413
AIOT Botania: 1.16.4-1.7.2
Modpack: valhElsia 3 3.2.0b

**Describe the bug**
I'm able to use the terrasteel aiot to take down a full tree in one block like the terrasteel axe.

**How to reproduce**
1. Grab terra axe use on tree. Mines whole tree from one block.
2. Grab terrasteel aiot. mine tree only breaks one block

**Expected behavior**
Terrasteel aiot would mine whole tree from one block like the terrasteel axe.

**Comment by phillipnielsen** [comment]
Not 100%sure if it's a bug or if that's just how it's supposed to work

**Comment by MelanX** [comment]
Did you activate the AIOT? 
For me it works when the AIOT is activated, if deactivated it's only one log

**Comment by phillipnielsen** [comment]
I am unable to find anything that deals with the terrasteel aiot. So I am unsure how you go about activating it

**Comment by phillipnielsen** [comment]
Just figured it out. It didn't work until I threw it into a mana pool and got it to grade b. After that I was able to right click the air and it worked. But it would be nice to have somewhere that state what is needed to do to use it properly. Sorry for the waste of time...

**Comment by MelanX** [comment]
Maybe this should be changed to be available without the need of mana. And without needing to activate it.
