### ISSUE TITLE
[1.16.5] Veinmining with Livingrock Shears stops blocks from dropping blocks

### ISSUE THREAD

**Issue by NielsPilgaard** [MelanX/aiotbotania#65]
**Versions**

Minecraft: 1.16.5
Forge: 1.16.5-36.1.13
Botania: Botania-1.16.5-415
AIOT Botania: aiotbotania-1.16.4-1.7.5
Modpack: Enigmatica 6 v0.4.10-indev

**Describe the bug**
Using Ultimine (veinmining) with Livingrock Shears causes all blocks to no longer drop anything.

**How to reproduce**

1. Make an instance with AIOT Botania and FTB Ultimine
2. With a papir of Livingrock Shears in-hand, hold the Ultimine keybinding
3. Destroy grass
3. See issue

**Expected behavior**
For grass to drop

Relevant part in log is line `14089`
[latest.log](https://github.com/MelanX/aiotbotania/files/6410258/latest.log)

**Comment by MelanX** [comment]
Can't reproduce with only FTB Ultimine and AIOT Botania. Needs to be another problem with other mod. I saw something with SimpleFarming.. maybe this is the problem. But only AIOT Botania and FTB Ultimine works fine.
In Enigmatica 6 0.4.10 I can reproduce it. Even when updating the mods to the version I used for testing.

**Comment by MelanX** [comment]
Tried in Enigmatica 0.5.17 and it works now. I still have no idea but I see this as resolved.
