### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by MelanX** [MelanX/aiotbotania#68]
I want to change to license from MIT License to Apache 2.0 License. More information can be found here: https://www.apache.org/licenses/LICENSE-2.0.txt

Before I change it, I need permissions from all contributors of this project. All the users below, do you agree the change to Apache 2.0?
- [x] @derkalaender 
- [x] @noeppi-noeppi 
- [x] @Ridanisaurus 
- [x] @yappy2000d 
- [x] @flier268 
- [ ] @DYColdWind 
- [ ] @Imbarainbow 
- [ ] @derNiklaas 
- [x] Vik (on Discord)

**Comment by derkalaender** [comment]
Approve 👍🏻

**Comment by noeppi-noeppi** [comment]
I approve that you change the license to Apache 2.0 for the project aiotbotania.

**Comment by flier268** [comment]
Approve

noeppi_noeppi ***@***.***> 於 2021年9月11日 週六 20:10 寫道：

**Comment by Ridanisaurus** [comment]
It makes no difference for me. It's your call.

**Comment by MelanX** [comment]
> It makes no difference for me. It's your call.

Yes, but I have to ask all contributors. And I have to hope that everyones approving the change.

**Comment by Ridanisaurus** [comment]
Sorry if I wasn't clear on my previous message. Approved.

**Comment by MelanX** [comment]
Reminder for @yappy2000d @DYColdWind @Imbarainbow and @derNiklaas. 
Everyone else could unsubscribe this thread in case they feel bothered.
![image](https://user-images.githubusercontent.com/26039509/158076631-e3959114-c994-4d2b-b254-5af73fba248f.png)

**Comment by yappy2000d** [comment]
Approve too!㊗

MelanX ***@***.***> 於 2022年7月31日 週日 下午3:20寫道：
