### ISSUE TITLE
Stone of Temperance support for Terrasteel AIOT Truncator

### ISSUE THREAD

**Issue by tlitookilakin** [MelanX/aiotbotania#69]
**Is your feature request related to a problem? Please describe.**
The terrasteel aiot is a fantastic tool, but because the only way to disable tree-mining is by holding crouch, it can be a pain to use for remodeling a base. In regular botania, the Truncator can be tamed by having an 'enabled' [Stone of Temperance](https://botaniamod.net/lexicon.php#temperanceStone) in your inventory, removing the need to hold crouch the whole time. 

**Describe the solution you'd like**
Currently, the Stone of Temperance has no effect on the tree-chopping effect of the AIOT, as might be expected. It would be nice if this could be added. In other words, having an active stone of temperance in your inventory would prevent the tree-chopping effect entirely.

**Describe alternatives you've considered**
I know originally the effect could be enabled/disabled by right-clicking on air, however, going through the commits, it seems that was changed due to being too confusing for players. The other alternative I can think of would be using a hotkey to toggle, and while it is more convenient than the stone of temperance, whether it is implemented or not, players are likely still expecting the stone of temperance to have some effect on the tree-chopping of the AIOT.

**Comment by tlitookilakin** [comment]
Looking at the source, it should be as simple as importing the temperance stone from botania and adding
`&& !ItemTemperanceStone.hasTemperanceActive(player)`
to [line 331](https://github.com/MelanX/aiotbotania/blob/4bcc5a39716102c21dd5c8a529fb27af6d5ef063/src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java#L331)

**Comment by tlitookilakin** [comment]
I've created a modified fork so I could build a version with this change made, but it's a trivial edit, so I won't create a pull request for it unless you'd like me to. I've tested it with the change and it seems to be working as expected.

**Comment by MelanX** [comment]
Thank you very much, will be fixed soon.

**Comment by tlitookilakin** [comment]
thank you very much :)
