### ISSUE TITLE
Tools missing from forge tags on 1.19.2 Plus

### ISSUE THREAD

**Issue by ModernGamingWorld** [MelanX/aiotbotania#76]
### Describe your idea

Hoes missing from forge:tools/hoes & forge:hoes tag
Pickaxes missing from forge:tools/pickaxes & forge:pickaxes tag 
Shovel missing from forge:tools/shovels & forge:shovels tag 
Axes missing from forge:tools/axes & forge:axes tag 
Swords missing from forge:tools/swords & forge:swords tag 

This would allow your recipes to work with other mods that use these tags and save us Modpack developers having to add them ourselves

**Comment by MelanX** [comment]
What’s the difference between `forge:tools/axes` and `forge:axes`? I see no reason to add both. If there is a difference for Modpack authors, please tell me. Then I could add it in my other mods as well, because all have just one of these.

**Comment by MelanX** [comment]
There were only the tags with `tools/` in front.
