### ISSUE TITLE
Neoforge Versioning Issue

### ISSUE THREAD

**Issue by LegitGamer1017** [MelanX/aiotbotania#80]
### Minecraft version

None

### AIOT Botania version

1.20.1-4.0.4

### Botania version

1.20.1-443

### Forge version

NEOFORGE 47.1.101

### The latest.log file

https://gist.github.com/LegitGamer1017/33c1d9180d6007e34f5efd9916027a84

### Issue description

Is this mod compatible with Neoforge + Forge?

I'm running a modpack with NeoForge 47.1.101, but it seems like your mod is searching for regular Forge 47.2.0 or above. 

With the different versioning numbers between the two, it causes the server to quit upon launch.

**Comment by MelanX** [comment]
Try 1.20.1-4.0.5. If it works, please close this issue. If it doesn’t work, please tell me and close this issue. In any way, I’m not trying to adjust the code to be compatible, just the required forge version. NeoGradle support may come in future!

**Comment by LegitGamer1017** [comment]
looks like this worked. Server starts normally!
