### ISSUE TITLE
Crash when shift right clicking on grass/dirt

### ISSUE THREAD

**Issue by TysonTheEmber** [MelanX/aiotbotania#81]
### Minecraft version

1.18.2

### AIOT Botania version

2.1.2

### Botania version

435

### Forge version

40.2.18

### The latest.log file

https://pastebin.com/4WLEZLvX

### Issue description

Crash when shift right clicking on grass/dirt

**Comment by MelanX** [comment]
Can't reproduce using your given "Steps to reproduce".

**Comment by TysonTheEmber** [comment]
1. Open World
2. get any aiot
3. SHIFT-RIGHT CLICK on block(any)
4. Instant crash
Modlist listed at end of log- https://bytebin.lucko.me/yeVRcrc52F
